#!/usr/bin/env python
#
# An xwax-albumart converter script

# able to parse folders and files
#
# By: Kenneth Allan
#

import sys,os,re
sys.path.append( "/home/tux/PyLib" )
import optionparse
from wichtig import *

befehl = sys.argv[0]
usage = """
Call: %s
Usage:	 
    An xwax-albumart converter script

    Options:
        -help  : Displays this
        -debug : View Debug Output (use this if you experience any weird
         behaviour)
""" % befehl

abb = '%(befehl)s: ABBRUCH '%locals()
warnung = '%(befehl)s: WARNUNG: '%locals()

opts, args = optionparse.parse( usage )

if opts.help: # or len(args) != 0:
    print usage
    sys.exit(1)

def search_subdirs(dir):
    imglist = []
    root, dirs, files = os.walk(dir)
    for f in files:
        if (f.endswith('.jpg')):
            imglist.add(f)
    for img in imglist:
        inp =  input('would you like to use %(img)s?'%locals())
            if (inp == ('yes' || 'y')):
                # TODO convert and backup (folder.orig.jpg)
                # nad exit loop

    pass


for arg in args:
    if not os.path.isdir(arg):
        break
    else:
        if not(os.path.exists( arg + "folder.orig.jpg" )):
            search_subdirs(arg)    